### ISSUE TITLE
latest master fails to build on ubuntu 18.04. 

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#2543]
Affects versions :

    OS: ubuntu 18.04

Describe the bug
after running:

`cmake`

end up with:

```
xournalpp/build/external/Source/ghcFilesystem_git/include/ghc/filesystem.hpp: In instantiation of ‘ghc::filesystem::path& ghc::filesystem::path::append(const Source&) [with Source = std::basic_string_view<char>]’:
/home/pgroszko/xournalpp/build/external/Source/ghcFilesystem_git/include/ghc/filesystem.hpp:2406:25:   required from ‘ghc::filesystem::path& ghc::filesystem::path::operator/=(const Source&) [with Source = std::basic_string_view<char>]’
/home/pgroszko/xournalpp/src/util/PathUtil.cpp:163:18:   required from here
/home/pgroszko/xournalpp/build/external/Source/ghcFilesystem_git/include/ghc/filesystem.hpp:2412:48: error: no matching function for call to ‘toUtf8(const std::basic_string_view<char>&)’
     return this->operator/=(path(detail::toUtf8(source)));
                                  ~~~~~~~~~~~~~~^~~~~~~~
/home/pgroszko/xournalpp/build/external/Source/ghcFilesystem_git/include/ghc/filesystem.hpp:1573:20: note: candidate: template<class charT, class traits, class Alloc, typename std::enable_if<(sizeof (charT) == 1), int>::type size> std::__cxx11::string ghc::filesystem::detail::toUtf8(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
 inline std::string toUtf8(const std::basic_string<charT, traits, Alloc>& unicodeString)
                    ^~~~~~
/home/pgroszko/xournalpp/build/external/Source/ghcFilesystem_git/include/ghc/filesystem.hpp:1573:20: note:   template argument deduction/substitution failed:
/home/pgroszko/xournalpp/build/external/Source/ghcFilesystem_git/include/ghc/filesystem.hpp:2412:48: note:   ‘const std::basic_string_view<char>’ is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
     return this->operator/=(path(detail::toUtf8(source)));
[...]
src/util/CMakeFiles/util.dir/build.make:182: recipe for target 'src/util/CMakeFiles/util.dir/PathUtil.cpp.o' failed
make[2]: *** [src/util/CMakeFiles/util.dir/PathUtil.cpp.o] Error 1
CMakeFiles/Makefile2:465: recipe for target 'src/util/CMakeFiles/util.dir/all' failed
make[1]: *** [src/util/CMakeFiles/util.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

The build does not complete. 
This has been a problem for some number of weeks now... maybe two or three. 
Thanks.

[CMakeError.log](https://github.com/xournalpp/xournalpp/files/5697513/CMakeError.log)
[CMakeOutput.log](https://github.com/xournalpp/xournalpp/files/5697514/CMakeOutput.log)

**Comment by Technius** [comment]
Is this a clean build?

**Comment by petergthatsme** [comment]
yup, clean build via:
```
git clone http://github.com/xournalpp/xournalpp.git
cd xournalpp
mkdir build
cd build
cmake ..
cmake --build .
```

**Comment by Technius** [comment]
One possible cause is ` 925acf9`. Can you try a commit earlier than it?

**Comment by petergthatsme** [comment]
yup, that's it. Tried `891c972c` and everything builds fine, then tried `925acf9e` and it fails with the error i show above.

**Comment by Technius** [comment]
@Febbe I think this a regression caused by upgrading `ghc::filesystem` to 1.3.8, can you confirm?

**Comment by Febbe** [comment]
>
>
> @Febbe I think this a regression caused by upgrading `ghc::filesystem` to 1.3.8, can you confirm?

Yes, this is correct, it may be fixed in version 1.3.10. I reported this for macOS (and made a workaround in the code for macOS). Didn't expect that this happens for gcc-7/gcc-8 either...

**Comment by Febbe** [comment]
@petergthatsme @Technius should be fixed now. Hopefully the pipeline will work tonight.

**Comment by petergthatsme** [comment]
yup, all good now. thanks.

**Comment by petergthatsme** [comment]
it looks like this is again a problem in the latest master branch. On ubuntu 18.04, i see:

```
cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.10.2

```
thanks.

**Comment by Febbe** [comment]
I propose to upgrade to latest Ubuntu
