### ISSUE TITLE
Fails to build with poppler 0.57 on Debian

### ISSUE THREAD

**Issue by inducer** [xournalpp/xournalpp#245]
```
/home/andreas/pack/xournalpp/src/pdf/popplerdirect/PdfRefList.cpp:120:57: error: no matching function for call to 'Dict::getVal(int&)'
   Object* contentsObject = new Object(dataDict->getVal(u));
                                                         ^
In file included from /usr/include/poppler/Object.h:321:0,
                 from /usr/include/poppler/Catalog.h:43,
                 from /home/andreas/pack/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/andreas/pack/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/andreas/pack/xournalpp/src/pdf/popplerdirect/PdfObjectWriter.h:17,
                 from /home/andreas/pack/xournalpp/src/pdf/popplerdirect/PdfRefList.h:14,
                 from /home/andreas/pack/xournalpp/src/pdf/popplerdirect/PdfRefList.cpp:1:
/usr/include/poppler/Dict.h:85:11: note: candidate: Object* Dict::getVal(int, Object*)
   Object *getVal(int i, Object *obj);
           ^~~~~~
/usr/include/poppler/Dict.h:85:11: note:   candidate expects 2 arguments, 1 provided
src/CMakeFiles/xournalpp-core.dir/build.make:4214: recipe for target 'src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfObjectWriter.cpp.o' failed
```

**Comment by JiahuiCai** [comment]
Similar issues here

/home/jack/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘void PdfExport::writeGzStream(Stream*, GList*)’:
/home/jack/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:287:48: error: no matching function for call to ‘Dict::lookup(const char [7])’
  Object obj1 =  str->getDict()->lookup("Length");
                                                ^
In file included from /usr/include/poppler/Object.h:302:0,
                 from /usr/include/poppler/Catalog.h:42,
                 from /home/jack/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/jack/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/jack/xournalpp/src/model/Document.h:20,
                 from /home/jack/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/jack/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/jack/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided

**Comment by piegamesde** [comment]
Same on poppler 0.48.0 with Debian Stretch

```
[[[ 90%] Building CXX object src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfBookmark.cpp.o
[ 90%] Building CXX object src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘void PdfExport::writeGzStream(Stream*, GList*)’:
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:287:48: error: no matching function for call to ‘Dict::lookup(const char [7])’
  Object obj1 =  str->getDict()->lookup("Length");
                                                ^
In file included from /usr/include/poppler/Object.h:314:0,
                 from /usr/include/poppler/Catalog.h:43,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/$USER/Downloads/xournalpp/src/model/Document.h:20,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^~~~~~
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘void PdfExport::writePlainStream(Stream*, GList*)’:
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:316:47: error: no matching function for call to ‘Dict::lookup(const char [7])’
  Object obj1 = str->getDict()->lookup("Length");
                                               ^
In file included from /usr/include/poppler/Object.h:314:0,
                 from /usr/include/poppler/Catalog.h:43,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/$USER/Downloads/xournalpp/src/model/Document.h:20,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^~~~~~
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘bool PdfExport::addPopplerPage(XojPopplerPage*, XojPopplerDocument)’:
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:474:43: error: no matching function for call to ‘Page::getContents()’
  Object* o = new Object(page->getContents());
                                           ^
In file included from /usr/include/poppler/PDFDoc.h:51:0,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:18,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/$USER/Downloads/xournalpp/src/model/Document.h:20,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Page.h:196:11: note: candidate: Object* Page::getContents(Object*)
   Object *getContents(Object *obj) { return contents.fetch(xref, obj); }
           ^~~~~~~~~~~
/usr/include/poppler/Page.h:196:11: note:   candidate expects 1 argument, 0 provided
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:480:40: error: no matching function for call to ‘Dict::lookup(const char [7])’
   Object filter = dict->lookup("Filter");
                                        ^
In file included from /usr/include/poppler/Object.h:314:0,
                 from /usr/include/poppler/Catalog.h:43,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/$USER/Downloads/xournalpp/src/model/Document.h:20,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^~~~~~
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:506:48: error: no matching function for call to ‘Object::arrayGet(int&)’
    Object* subObject = new Object(o->arrayGet(i));
                                                ^
In file included from /usr/include/poppler/Catalog.h:43:0,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/$USER/Downloads/xournalpp/src/model/Document.h:20,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Object.h:304:16: note: candidate: Object* Object::arrayGet(int, Object*, int)
 inline Object *Object::arrayGet(int i, Object *obj, int recursion = 0)
                ^~~~~~
/usr/include/poppler/Object.h:304:16: note:   candidate expects 3 arguments, 1 provided
/home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:511:42: error: no matching function for call to ‘Dict::lookup(const char [7])’
     Object filter = dict->lookup("Filter");
                                          ^
In file included from /usr/include/poppler/Object.h:314:0,
                 from /usr/include/poppler/Catalog.h:43,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerPage.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/poppler/XojPopplerDocument.h:14,
                 from /home/$USER/Downloads/xournalpp/src/model/Document.h:20,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfBookmark.h:15,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.h:14,
                 from /home/$USER/Downloads/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:1:
/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^~~~~~
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
src/CMakeFiles/xournalpp-core.dir/build.make:4190: recipe for target 'src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o' failed
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o] Error 1
CMakeFiles/Makefile2:348: recipe for target 'src/CMakeFiles/xournalpp-core.dir/all' failed
make[1]: *** [src/CMakeFiles/xournalpp-core.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2](url)
](url)
```

**Comment by andreasb242** [comment]
There are some fixes merged to the master, therefore I close this ticket no. If the bug still exists, reopen.
