### ISSUE TITLE
poppler workaround and build with v 0.71.0

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#283]
Hey,
When compiling with poppler 0.71.0 CairoOutputDevice can not be linked anymore.

```
/usr/bin/ld: CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/poppler/XojPopplerDocument.cpp.o: in function `_IntPopplerDocument::_IntPopplerDocument(PDFDoc*)':
/home/peetcreative/study/openSoftHardware/xournalpp-golvok/src/pdf/popplerdirect/poppler/XojPopplerDocument.cpp:27: undefined reference to `CairoOutputDev::CairoOutputDev()'
/usr/bin/ld: /home/peetcreative/study/openSoftHardware/xournalpp-golvok/src/pdf/popplerdirect/poppler/XojPopplerDocument.cpp:28: undefined reference to `CairoOutputDev::startDoc(PDFDoc*, CairoFontEngine*)'
/usr/bin/ld: CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/poppler/XojPopplerPage.cpp.o: in function `XojPopplerPage::render(_cairo*, bool)':
/home/peetcreative/study/openSoftHardware/xournalpp-golvok/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:96: undefined reference to `CairoOutputDev::setCairo(_cairo*)'
/usr/bin/ld: /home/peetcreative/study/openSoftHardware/xournalpp-golvok/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:106: undefined reference to `CairoOutputDev::setTextPage(TextPage*)'
/usr/bin/ld: /home/peetcreative/study/openSoftHardware/xournalpp-golvok/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:125: undefined reference to `CairoOutputDev::setCairo(_cairo*)'
/usr/bin/ld: /home/peetcreative/study/openSoftHardware/xournalpp-golvok/src/pdf/popplerdirect/poppler/XojPopplerPage.cpp:126: undefined reference to `CairoOutputDev::setTextPage(TextPage*)'
```

Recently (pullrequest #265) and in the past (issue #138) it has been discussed that we use in XojPopplerPage CairoOutputDev. I'm not sure why the workaround does not work anymore.

@andreasb242 wrote on #265
> The only thing to solve this problem would be to add an official API to poppler, which supports the PDF editing as we need it official. Did you check already if they maybe would accept such a pull request? (I mailed them sometimes, but this is now 7 Years ago...)
>  Or the other alternative, create subfolders for different poppler versions (or maybe only defines within the files), and include always the right version. But this would mean to duplicate the code.

I don't know exactly now exactly what xournalpp is using with CairoOutputDev for. Most probably we use poppler to also manipulate PDF. I would look how CairoOutputDevice is used in Poppler maybe also one can adapt to official API. But I don't know poppler by now enough. I would contact poppler team on this.
And I don't get exactly the alternative. Isn't it that what master is just doing it now in `src/pdf/popplerdirect/workaround`?

**Comment by andreasb242** [comment]
The main Problem: we use Poppler the wrong way, Poppler is a PDF viewer Library, not a PDF Manipulation library.

The History behind it:
Poppler is the common PDF display Library, that's the reason why I used this for PDF displaying.
Xournal simple printed the PDF, and then Printed the Annotated Contents, which workflow bookmark, links and everything else will be lost.
I looked at the Poppler source, and recognized that it is not so hard to use them for editing, the headers where installed on my System, so it wasn't a problem.
After the next distribution update, the header were removed, I asked the Poppler team why, and they told me they are not official, I should use one of the APIs, but none of the APIs allow to edit PDFs that way Xournal++ used it.

>And I don't get exactly the alternative. Isn't it that what master is just doing it now in src/pdf/popplerdirect/workaround?
The workaround is not done by me, but it is simple a static build which is linked, and which allow to access the private headers again. Currently the best solution available with less work.

There are two possibilities:
Use a complete different library for editing PDFs: In my opinion makes no sense, really much work, double load the PDF etc.

> I would look how CairoOutputDevice is used in Poppler maybe also one can adapt to official API. But I don't know poppler by now enough. I would contact poppler team on this.
That would be my prefered choice, but I'm not sure if Poppler would accept such an API

But I'm also open to other solutions... (if there any)

@peetCreative Thank you for working on this issue!

**Comment by badshah400** [comment]
FWIW, distros seem to not be distributing the internal header `poppler/CairoOutputDev.h` at all because it is an internal header and not installed by poppler's autotools installer. Consequently, when trying to build on openSUSE, one sees an error like this:
```
[  215s] /home/abuild/rpmbuild/BUILD/xournalpp-gtk3-1.99.20181111.96b64738/src/pdf/popplerdirect/workaround/workaround.h:3:10: fatal error: poppler-0.62.0/poppler/CairoOutputDev.h: No such file or directory
[  215s]  #include "poppler-0.62.0/poppler/CairoOutputDev.h"
[  215s]           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  215s] compilation terminated.
```

Any suggestions on how to work around this will be greatly appreciated. Thanks!

**Comment by andreasb242** [comment]
The same on Ubuntu, but they did some time ago!

However, did you try the flag **-DBUILD_POPPLER=ON**?

**Comment by badshah400** [comment]
Using `-DBUILD_POPPLER=ON` was not really an option because I am trying to build RPM packages for openSUSE on the [build service](https://build.opensuse.org/) and it does not allow build tools to access the internet and download necessary sources (AFAICT this was needed until #302 to get poppler from git). Will try to do this now that #302 is committed.

**Comment by andreasb242** [comment]
Hi @badshah400, the Pull is merged.
If you have created RPM packages, please let me know, we should add a Link e.g. the main Readme file.

**Comment by badshah400** [comment]
Sorry, still doesn't seem to work here. I am passing `-DBUILD_POPPLER=ON -DPOPPLER_GIT=OFF -DPOPPLER_DIR="../"` to cmake point to the poppler 0.68.0 source tarball (unextracted). This actually works up to a point: cmake does build poppler as expected; but then it still complains about the missing `poppler-0.68.0/poppler/CairoOutputDev.h` header file. Indeed that header file does not seem to exist anywhere in the build directory. It is in the source tarball though.

**Comment by peetCreative** [comment]
@badshah400 But at the extracted poppler is located at `../`? 
Because I think this option is just taking the source form `POPPLER_DIR` and compiles it into `poppler-prefix` folder.
Maybe one can add an option to extract the tarball first. Than it might work.
But I'm thinking for the first forcing to build poppler manually if the poppler is above 0.68

**Comment by andreasb242** [comment]
I use now the standard GLib APi, and export the PDF with Cairo.
The old implementation will still be available with -DADVANCED_PDF_EXPORT_POPPLER=ON
Currently Bookmarks are not exported, but with Cairo 1.16 it will also be possible.
So this should solve a lot of problems I hope.

**I Copy this texts to all related tickets **

**Comment by badshah400** [comment]
Many thanks for fixing this. I will give it a try in the next few days and confirm.

@peetCreative Sorry, I missed your previous message. It turns out that the poppler source tarball was not being extracted at all, as you have rightly figured out. Thanks to you for the help as well.

**Comment by badshah400** [comment]
Total success in building packages from git master! Thanks everyone.
https://build.opensuse.org/package/show/home:badshah400:Staging/xournalpp-gtk3

**Comment by andreasb242** [comment]
Hi @badshah400 

Is the build running automatically every day or so?
Can we link this on the start page as Official Build for OpenSuse?

I plane the same for Ubuntu...

**Comment by andreasb242** [comment]
I added it to the main Readme

**Comment by badshah400** [comment]
Sorry for the late response. The build runs semi-automatically, i.e. I need to "trigger" the services to download the latest git master and from there on the build happens automatically. Typically, I do the triggering part once a day or every two days unless I am away on vacation on something (which was the case for the last couple of weeks).

Thanks for linking it to the main readme. Once there is a new tagged release, I intend to submit xournalpp to the official openSUSE release channel so that folks using openSUSE will be able to install it directly from the package-manager and so on.

**Comment by andreasb242** [comment]
I'm planing to do an official release soon, there is one Windows bug which I would fix before.

**Comment by badshah400** [comment]
Awesome news! Many thanks and cheers!

**Comment by andreasb242** [comment]
@badshah400 I created a release: https://github.com/xournalpp/xournalpp/releases/tag/1.0.5

**Comment by badshah400** [comment]
Thanks again. On its way to becoming available on default openSUSE channels:
https://build.opensuse.org/request/show/662113

**Comment by andreasb242** [comment]
Thank you!
