### ISSUE TITLE
/pdf/popplerdirect/PdfExport.cpp.o Error 1

### ISSUE THREAD

**Issue by rickvek** [xournalpp/xournalpp#234]
Got an error running cmake.:
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:4191: src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
How to solve this??

Gr.Rick

**Comment by rickvek** [comment]
additional information:
Platform used : 4.13.9-200.fc26.x86_64
  poppler.x86_64 0.52.0-9.fc26          poppler-glib.x86_64 0.52.0-9.fc26      
  poppler-qt5.x86_64 0.52.0-9.fc26      poppler-utils.x86_64 0.52.0-9.fc26

**Comment by rickvek** [comment]
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘void PdfExport::writeGzStream(Stream*, GList*)’:
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:287:48: error: no matching function for call to ‘Dict::lookup(const char [7])’
  Object obj1 =  str->getDict()->lookup("Length");

/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘void PdfExport::writePlainStream(Stream*, GList*)’:
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:316:47: error: no matching function for call to ‘Dict::lookup(const char [7])’
  Object obj1 = str->getDict()->lookup("Length");

/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp: In member function ‘bool PdfExport::addPopplerPage(XojPopplerPage*, XojPopplerDocument)’:
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:474:43: error: no matching function for call to ‘Page::getContents()’
  Object* o = new Object(page->getContents());

/usr/include/poppler/Page.h:196:11: note:   candidate expects 1 argument, 0 provided
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:480:40: error: no matching function for call to ‘Dict::lookup(const char [7])’
   Object filter = dict->lookup("Filter");

/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^~~~~~
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:506:48: error: no matching function for call to ‘Object::arrayGet(int&)’
    Object* subObject = new Object(o->arrayGet(i));
                                                ^

/usr/include/poppler/Object.h:304:16: note: candidate: Object* Object::arrayGet(int, Object*, int)
 inline Object *Object::arrayGet(int i, Object *obj, int recursion = 0)
                ^~~~~~
/usr/include/poppler/Object.h:304:16: note:   candidate expects 3 arguments, 1 provided
/home/rickvek/GitRepos/xournal/xournalpp/src/pdf/popplerdirect/PdfExport.cpp:511:42: error: no matching function for call to ‘Dict::lookup(const char [7])’
     Object filter = dict->lookup("Filter");

/usr/include/poppler/Dict.h:79:11: note: candidate: Object* Dict::lookup(const char*, Object*, int)
   Object *lookup(const char *key, Object *obj, int recursion = 0);
           ^~~~~~
/usr/include/poppler/Dict.h:79:11: note:   candidate expects 3 arguments, 1 provided
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:4191: src/CMakeFiles/xournalpp-core.dir/pdf/popplerdirect/PdfExport.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by peetCreative** [comment]
mh... in poppler 0.58 some declaration have changed. Run cmake with -BUILD_POPPLER. This should compile the new version of poppler.

**Comment by shuhaowu** [comment]
Can confirm this bug as well on the latest commit, -DBUILD_POPPLER=ON works for the first call of `make`. Subsequent calls seems to give 

```
Failed to unstash changes in:
  '/projects/xournalpp/build/poppler-prefix/src/poppler/'.

```

Looks like the poppler source directory is being changed as it is built with BUILD_POPPLER.

**Comment by andreasb242** [comment]
No updates since a year, and the current build works with -DBUILD_POPPLER=ON on Ubuntu 16.04
