### PR TITLE
Fix backtrace linker flags

### LINKED ISSUE #3817: undefined reference to `backtrace_symbols` (missing `-lexecinfo` on musl libc)
When upgrading the void package of xournalpp to 1.1.1 (https://github.com/void-linux/void-packages/pull/35621) we noted the following build failure using musl libc:
```
...
/usr/bin/ld: src/xoj-preview-extractor/CMakeFiles/xournalpp-thumbnailer.dir/__/util/Stacktrace.cpp.o: in function `Stacktrace::printStracktrace(std::ostream&)':
Stacktrace.cpp:(.text+0x24a): undefined reference to `backtrace'
/usr/bin/ld: Stacktrace.cpp:(.text+0x25f): undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
...
```

This is caused by a missing `-lexecinfo` when linking `xournalpp-thumbnailer`. The issue is new in 1.1.1 because this binary now links with `src/util/Stacktrace.cpp`.

The following patch seems to fix the issue:
```
--- a/src/xoj-preview-extractor/CMakeLists.txt	2022-02-13 16:30:45.000000000 -0300
+++ b/src/xoj-preview-extractor/CMakeLists.txt	2022-02-14 16:03:48.561654740 -0300
@@ -35,6 +35,7 @@
   ${librsvg_LDFLAGS}
   ${Glib_LDFLAGS}
   ${ZIP_LDFLAGS}
+  ${Backtrace_LIBRARIES}
   )
 
 target_include_directories (xournalpp-thumbnailer PRIVATE ${librsvg_INCLUDE_DIRS})
```

### PR DESCRIPTION
**Pull request by Technius**
Fixes #3817.

### CODE REVIEW

**Comment by Technius** [comment]
This should not be a problem on current master branch.

**Comment by Technius** [comment]
Merging in 24 hours if there are no objections.
