### ISSUE TITLE
src/util/PathUtil.cpp:214:28: error: ‘relative’ is not a member of ‘fs’

### ISSUE THREAD

**Issue by rikigigi** [xournalpp/xournalpp#2212]
**Affects versions :**
 - OS: linux
 - Version of Xournal++: master, commit 45184492057387fde4319358e8c2dc4c7ae5b80b
 - compiled from git
 -  gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Describe the bug**
```
mkdir build; cd build; cmake ../
$ make
[  1%] Build translations.
[ 21%] Built target translations
[ 21%] Building CXX object src/util/CMakeFiles/util.dir/PathUtil.cpp.o
/home/bertossa/xournalpp/src/util/PathUtil.cpp: In function ‘bool Util::isChild(const std::experimental::filesystem::v1::__cxx11::path&, const std::experimental::filesystem::v1::__cxx11::path&)’:
/home/bertossa/xournalpp/src/util/PathUtil.cpp:214:28: error: ‘relative’ is not a member of ‘fs’
            *std::begin(fs::relative(path, base)) != "..";
                            ^~~~~~~~
src/util/CMakeFiles/util.dir/build.make:206: recipe for target 'src/util/CMakeFiles/util.dir/PathUtil.cpp.o' failed
make[2]: *** [src/util/CMakeFiles/util.dir/PathUtil.cpp.o] Error 1
CMakeFiles/Makefile2:426: recipe for target 'src/util/CMakeFiles/util.dir/all' failed
make[1]: *** [src/util/CMakeFiles/util.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```
**To Reproduce**
try to compile on ubuntu 18.04.5 LTS

**Expected behavior**
compilation is ok

**Comment by rolandlo** [comment]
Which compiler version do you use? The relative member for filepath has been introduced with C++17, see [this link](https://en.cppreference.com/w/cpp/filesystem/relative).

**Comment by rikigigi** [comment]
By the way, after setting CXX_FILESYSTEM_HAVE_FS to false with cmake-gui, it compiles without any problem, maybe the cmake file can be improved!

**Comment by Febbe** [comment]
Officially we support gcc7/g++7 thats true, so either we should drop the support. Or we have to use the [gulrak filesystem library](https://github.com/gulrak/filesystem). But @rikigigi in both cases I can recommend to use gcc-8/g++-8 | clang-8 or higher.

I propose to drop the support soon, since c++20 knocks on the door and the old Ubuntu LTS (18.04) delivers g++-8 over `apt`.
@LittleHuba, @andreasb242 what do you think?

**Comment by Febbe** [comment]
@rikigigi can you try my PR?

**Comment by LittleHuba** [comment]
There was one case that forced gcc-7. Please check the major OSs and not just Ubuntu. Debian is a likely candidate.

**Comment by rikigigi** [comment]
> @rikigigi can you try my PR?

it compiles and runs fine, thanks!  :-)

**Comment by Febbe** [comment]
@rikigigi did you deleted your CMakeCache?

**Comment by rikigigi** [comment]
> @rikigigi did you deleted your CMakeCache?

I used a completely different folder

**Comment by Febbe** [comment]
Both debian(buster) and Ubuntu18.04 support gcc-8/g++8. I currently don't know whats about the other distributions. They are mostly handled by other volunteers am I right?
I think we could drop the official support of gcc7, but we try to still support it as long as we could. This would enable us to move to c++20 some day. I mostly looking forward to std::format and the spaceship operator. Also the lockfree atomic shared_ptr is a good improvement.
