### ISSUE TITLE
startup crash on macos

### ISSUE THREAD

**Issue by zjttoefs** [xournalpp/xournalpp#2836]
**Affects versions :**
 - installed with homebrew (version 1.0.20, "official" I guess)
 - MacOS 11.2.1
 - libgtk 3.24.10
 
**Describe the bug**
crash at startup, sometimes a UI window appears for a fraction of a second

**To Reproduce**
Steps to reproduce the behaviour:
1. brew install xournal-plus-plus
2. /Applications/Xournal++.app/Contents/MacOS/xournalpp
3. observe crash

**Expected behavior**

xournalpp opens the GUI and is ready to use

**Screenshots of Problem**

unable to take, window only opens for a fraction of a second

**Additional context**

errorlog is attached.
[errorlog.20210220-100136.log](https://github.com/xournalpp/xournalpp/files/6014472/errorlog.20210220-100136.log)

console output:

```
$ /Applications/Xournal++.app/Contents/MacOS/xournalpp
2021-02-20 10:01:35.432 defaults[45751:1348959]
The domain/default pair of (.GlobalPreferences, AppleCollationOrder) does not exist

** (com.github.xournalpp.xournalpp:45746): WARNING **: 10:01:35.969: Failed to load "colornames.ini" (/Users/svven/.xournalpp//colornames.ini): No such file or directory


** (com.github.xournalpp.xournalpp:45746): WARNING **: 10:01:36.391: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


(com.github.xournalpp.xournalpp:45746): GLib-GObject-WARNING **: 10:01:36.428: g_object_get_is_valid_property: object class 'GtkLabel' has no property named 'accel-closure'

(com.github.xournalpp.xournalpp:45746): Gtk-WARNING **: 10:01:36.694: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node marks owner GtkScale)

(com.github.xournalpp.xournalpp:45746): Gtk-WARNING **: 10:01:36.694: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(com.github.xournalpp.xournalpp:45746): Gtk-WARNING **: 10:01:36.694: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(com.github.xournalpp.xournalpp:45746): Gtk-WARNING **: 10:01:36.694: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(com.github.xournalpp.xournalpp:45746): Gtk-WARNING **: 10:01:36.694: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

** (com.github.xournalpp.xournalpp:45746): WARNING **: 10:01:36.745: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:45746): WARNING **: 10:01:36.745: [Crash Handler] Wrote crash log to: /Users/svven/.xournalpp/errorlogs/errorlog.20210220-100136.log
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found

** (com.github.xournalpp.xournalpp:45746): WARNING **: 10:01:36.835: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:45746): WARNING **: 10:01:36.836: Successfully saved document to "/Users/svven/.xournalpp//emergencysave.xopp"
$

```

**Comment by gaperez64** [comment]
Could you comment on your architecture? I can reproduce the bug but, in my case at least, this should be because of my M1 (ARM) architecture and the homebrew cask just downloading the mac x86-64 release.

Related? #2823

**Comment by zjttoefs** [comment]
My Mac is old enough that I did not think about that! It's a 2018 Intel Macbook Pro. Unrelated, I would say.

**Comment by zjttoefs** [comment]
The description in #2815 mentions 1.2.20 consistently crashing on startup as well.

**Comment by Febbe** [comment]
Can you retry with 1.1.0~dev?

**Comment by zjttoefs** [comment]
1.1.0.dev-nightly.20210221 crashes in pretty much the same way.

**Comment by Febbe** [comment]
We unfortunately do not have any macOs device. So we could need some help from the community. Do you know how to compile and run xournalpp in debug mode?

**Comment by zjttoefs** [comment]
I can give that a go. https://github.com/xournalpp/xournalpp/blob/nightly/readme/MacBuild.md should be up date, right?

**Comment by Febbe** [comment]
Maybe a dep is missing, but if it fails you could ask a question then I try to help & add it to the manual

**Comment by zjttoefs** [comment]
I very much looks like `nightly` is hopelessly out of date. While the 1.1.1.dev-nightly is build every night, the last commit to that tag stems from August 2019. Or am I getting confused?

I build master using the (non-recommended) homebrew route and needed to install `portaudio` and `libzip` in addition to the requirements listed. 
Camke found cairo includes in `/usr/local/Cellar/cairo/1.16.0_4/include/cairo` with the trailing `cairo`. In include statements include `cairo/cairo.h`, so they do not expect the trailing component. Not being a cmake expert, I fixed that with a symbolic link. 

With the changes above I managed to build the master branch and ended up with a working binary. Well, at least the application started and displayed something.

**Comment by rolandlo** [comment]
> It very much looks like `nightly` is hopelessly out of date. While the 1.1.0.dev-nightly is build every night, the last commit to that tag stems from August 2019. Or am I getting confused?

The `nightly` shouldn't be out of date. The thing is that only the assets get replaced and the source code (which is still from August 2019) doesn't match the assets.

**Comment by zjttoefs** [comment]
@rolandlo that is a little confusing, though. Not sure that's how other projects run their nightlies. 
What led me down the path to check what that my build of master works. So I tried to see if there was a diff between master and nightly. 

But I guess that tells us my problem is most likely in how nightly is build. Could be a problem with Big Sur. The automated build is on Catalina.

**Comment by nboelter** [comment]
The same crash with identically looking errorlog also happens on a 2017 MacBook Pro running Big Sur 11.2.1. 

The UI is also only drawn in the upper left corner of the window, the right and bottom 3/4 of the window are black, before it crashes. Maybe has something to do with one dot being 2x2 pixels.

The previous release seems to work though.

**Comment by SwiftWinds** [comment]
I `brew install binutils` after noticing that it was complaining that it couldn't find addr2line. However, it still crashes with a slightly different log:

```
2021-03-02 22:07:35.872 defaults[83881:7149807]
The domain/default pair of (.GlobalPreferences, AppleCollationOrder) does not exist

** (com.github.xournalpp.xournalpp:83876): WARNING **: 22:07:36.640: Failed to load "colornames.ini" (/Users/matt/.xournalpp//colornames.ini): No such file or directory


** (com.github.xournalpp.xournalpp:83876): WARNING **: 22:07:37.665: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


(com.github.xournalpp.xournalpp:83876): GLib-GObject-WARNING **: 22:07:37.719: g_object_get_is_valid_property: object class 'GtkLabel' has no property named 'accel-closure'

(com.github.xournalpp.xournalpp:83876): Gtk-WARNING **: 22:07:38.129: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node marks owner GtkScale)

(com.github.xournalpp.xournalpp:83876): Gtk-WARNING **: 22:07:38.129: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(com.github.xournalpp.xournalpp:83876): Gtk-WARNING **: 22:07:38.129: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(com.github.xournalpp.xournalpp:83876): Gtk-WARNING **: 22:07:38.129: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(com.github.xournalpp.xournalpp:83876): Gtk-WARNING **: 22:07:38.130: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)
Assertion failed: (!surface->finished), function _cairo_surface_release_source_image, file /Users/git-bin/gtk/source/cairo-1.16.0/src/cairo-surface.c, line 2092.

** (com.github.xournalpp.xournalpp:83876): WARNING **: 22:07:38.238: [Crash Handler] Crashed with signal 6

** (com.github.xournalpp.xournalpp:83876): WARNING **: 22:07:38.238: [Crash Handler] Wrote crash log to: /Users/matt/.xournalpp/errorlogs/errorlog.20210302-220738.log
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory
addr2line: Warning: '/Users/matt/Downloads/Xournal++.app/Contents/MacOS' is a directory

** (com.github.xournalpp.xournalpp:83876): WARNING **: 22:07:38.903: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:83876): WARNING **: 22:07:38.904: Successfully saved document to "/Users/matt/.xournalpp//emergencysave.xopp"
```

**Comment by LucaAngioloni** [comment]
I want to confirm and report the same behaviour on:

 - MacOS BigSur: 11.2.3 (20D91)
 - MacBook Pro (15-inch, 2018)
 - Installed from brew and directly downloaded from GitHub.

The app opens for a split second and draws the UI on the top left corner, and it crashed.
Same logs as above.
Cannot help on the build.

**Comment by rolandlo** [comment]
@LucaAngioloni Have you tried [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) as well? If it crashes as well, can you post the errorlog?

**Comment by ramet** [comment]
Same for me : 
- MacOS BigSur: 11.2.3
- MacBook Pro 13-inch 2016
- installed with Homebrew
- qt dependency is not set, I tried both with qt@5 and qt (version 6) installed with Homebrew

It crash immediately after drawing the UI.

The same when installed by hand using the nightly build...

**Comment by LucaAngioloni** [comment]
@rolandlo Same with the nightly build.

It works on version 1.0.19 though. I am using that one for the moment.

**Comment by ramet** [comment]
Yes it works with 1.0.19. I switch back to this release for the moment.

**Comment by rolandlo** [comment]
Thanks to acquiring a (7-year old) MacBook Pro I can now confirm the observations made here: 

- On BigSur version 1.0.19 runs fine, but versions 1.0.20 and version 1.1.0+dev don't.
- On Catalina versions 1.0.19, 1.0.20 and 1.1.0+dev all work fine.

I have also noticed two more things in version 1.1.0+dev:
- localizations don't work (I couldn't choose the language in the preferences)
- the old app icon is used (the xournalpp.icns file delivered with the  [xournalpp-1.1.0.dev-nightly.20210318-macos.zip](https://github.com/xournalpp/xournalpp/releases/tag/nightly) is outdated.

Once I find some time I will help to fix this on BigSur. It may take some time until I can build Xournal++ on MacOS, since I have no previous experience with MacOS.

**Comment by zjttoefs** [comment]
Building via homebrew on MacOS was actually quite trivial. That seems to have been a working setup in the past, but is stated as being no longer officially supported (https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md). My approach would be to just revert to brew and check if the above problems persist.

**Comment by gaperez64** [comment]
> Building via homebrew on MacOS was actually quite trivial. That seems to have been a working setup in the past, but is stated as being no longer officially supported (https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md). My approach would be to just revert to brew and check if the above problems persist.
> Edit: I checked - localisation does not work on the brew build of 1.1.0-dev either.

There are problems with gtk-mac-integration on the brew build too. It seems gtk+2 and gtk+3 get confused. I suppose the current mac build gets around this by building gtk from source?

**Comment by Febbe** [comment]
@zjttoefs building over homebrew was long ago the only way to run it on mac, but it was never supported as it should. The only thing which changed is, that we supply a official mac release which is standalone and does not require a package manager. Thus we marked the brew way as unsupported, since we never debugged problems with brew. We only care about our code compiling and running on macOs. So if it compiles and runs, it should compile and run also with brew, as long as the compatibility of the dependencies do not change.

**Comment by Febbe** [comment]
@gaperez64 yes, currently we build all deps over jhbuild as binary blob and only recompile xournalpp.

**Comment by Febbe** [comment]
Also happens on macOS 10.15 when compiling xournalpp v.1.1.0~dev from source with newest deps and AppleClang12.

**Comment by Febbe** [comment]
In my case it does not crash every 3rd attempt. It crashes in:

```
0   CoreFoundation                      0x00007fff3087a727 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff695e9a9e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3087a585 +[NSException raise:format:] + 181
	3   AppKit                              0x00007fff2da54fe2 -[NSCarbonMenuImpl _createMenuRef] + 55
	4   AppKit                              0x00007fff2da549b2 -[NSCarbonMenuImpl _instantiateCarbonMenu] + 133
	5   AppKit                              0x00007fff2da4d9d5 -[NSApplication finishLaunching] + 694
	6   libgtkmacintegration-gtk3.2.dylib   0x00000001026e3ab6 gtkosx_application_ready + 38
	7   xournalpp                           0x000000010018b3f3 _ZN10MainWindowC2EP15GladeSearchpathP7Control + 5363
	8   xournalpp                           0x000000010018cd05 _ZN10MainWindowC1EP15GladeSearchpathP7Control + 37
	9   xournalpp                           0x000000010006d197 _ZNSt3__1L11make_uniqueI10MainWindowJP15GladeSearchpathP7ControlEEENS_11__unique_ifIT_E15__unique_singleEDpOT0_ + 103
	10  xournalpp                           0x000000010006a91c _ZN12_GLOBAL__N_110on_startupEP13_GApplicationPNS_18XournalMainPrivateE + 1692
	11  libgobject-2.0.0.dylib              0x00000001023a16ad g_closure_invoke + 189
	12  libgobject-2.0.0.dylib              0x00000001023b7c20 signal_emit_unlocked_R + 1632
	13  libgobject-2.0.0.dylib              0x00000001023b8c1d g_signal_emit_valist + 2653
	14  libgobject-2.0.0.dylib              0x00000001023b9142 g_signal_emit + 130
	15  libgio-2.0.0.dylib                  0x00000001021df355 g_application_register + 293
	16  libgio-2.0.0.dylib                  0x00000001021e1b6b g_application_real_local_command_line + 1547
	17  libgtk-3.0.dylib                    0x000000010109b5bd gtk_application_local_command_line + 77
	18  libgio-2.0.0.dylib                  0x00000001021dfa68 g_application_run + 408
	19  xournalpp                           0x000000010006a166 _ZN11XournalMain3runEiPPc + 2262
	20  xournalpp                           0x000000010000a797 main + 39
	21  libdyld.dylib                       0x00007fff6a789cc9 start + 1
```

**Comment by Febbe** [comment]
**Note:** Version 1.1.0~dev does not require gtk_mac_integration anymore.
```
New Gtk3 applications should prefer the GApplication/GtkApplication and GMenuModel/GMenu APIs which make this library unnecessary.
```

But we need to use GMenu properly.

**Comment by Febbe** [comment]
Can you all test my fix?

**Comment by ramet** [comment]
> Can you all test my fix?

Thanks for your attempt to fix the bug. To try your patch, should we need to compile xournal by ourself, or is it possible to get a nightly build of your merge request ?

**Comment by Febbe** [comment]
You need to compile xournalpp by yourself with my source. Or wait, until my pr is reviewed and merged

**Comment by Febbe** [comment]
@ramet the fix should also work with brew, this will reduce your compile times. In case you don't want to checkout my changes, just remove all the code, using the gtk_mac_integration

**Comment by ramet** [comment]
> @ramet the fix should also work with brew, this will reduce your compile times. In case you don't want to checkout my changes, just remove all the code, using the gtk_mac_integration

You have a formula that build xournal-plus-plus from source ? The one I use is the one from Cask repository that only deals with binary.

**Comment by Febbe** [comment]
I compiled it via jhbuild, but that took hours (we require to use jhbuild for the releases), but you can just compile it with brew as basis.

For that, visit our [MacBuild wiki page](https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md#xournal-mac-homebrew-build) and follow the homebrew build instructions.

Also, those changes can be required:
https://github.com/xournalpp/xournalpp/pull/2973

**Comment by ramet** [comment]
I compile with brew dependencies, and it works successfully with your MR #2976 ! Many thanks :)
(FYI, I first try from the master branch, commit e702392f, but it fails during compilation with missing include path :
```
[ 68%] Building CXX object src/CMakeFiles/xournalpp-core.dir/gui/inputdevices/touchdisable/TouchDisableX11.cpp.o
/Users/ramet/Downloads/xournalpp/src/gui/inputdevices/touchdisable/TouchDisableX11.cpp:5:10: fatal error:
      'gdk/gdkx.h' file not found
#include <gdk/gdkx.h>
         ^~~~~~~~~~~~
```)
Hope, your patch will be merged.

**Comment by Febbe** [comment]
Hopefully, this wasn't just a corner case, only triggered by GtkMacIntegration, since it is a singleton. Then it just hid the real cause.

**Comment by mschinca** [comment]
@ramet I also hit the missing include path for
```
#include <gdk/gdkx.h>
         ^~~~~~~~~~~~
```
problem.
This change has been introduced in 0f994db .
In my case I built GTK with macports as suggested in #2390 and I could verify that this header file was missing in my local GTK build.
I didn't do much investigation, but I suspect this may be due to some GTK build options related to X11.
This header is also missing in the brew GTK package (using 3.24.28). You can check the output of:
```
brew ls -v gtk+3
```

@andreasb242  What was the purporse of 0f994db ?

In my case I found easier to revert the change:
```
diff --git a/src/gui/inputdevices/touchdisable/TouchDisableX11.cpp b/src/gui/inputdevices/touchdisable/TouchDisableX11.cpp
index 8aaeb6ad..bb56d1a7 100644
--- a/src/gui/inputdevices/touchdisable/TouchDisableX11.cpp
+++ b/src/gui/inputdevices/touchdisable/TouchDisableX11.cpp
@@ -2,8 +2,6 @@

 #ifdef X11_ENABLED

-#include <gdk/gdkx.h>
-
 TouchDisableX11::TouchDisableX11() = default;

 TouchDisableX11::~TouchDisableX11() {
@@ -12,13 +10,13 @@ TouchDisableX11::~TouchDisableX11() {
         touchdev = nullptr;
     }

-    display = nullptr;
+    display = NULL;
 }

 void TouchDisableX11::init() {
     // Get display from GTK
-    display = gdk_x11_display_get_xdisplay(gdk_display_get_default());
-    if (display == nullptr) {
+    display = XOpenDisplay(NULL);
+    if (display == NULL) {
         g_error("Could not open X11 display");
         return;
     }
```

**Comment by Febbe** [comment]
You should figure out, why `find_package(X11)` finds a X11 package on mac

**Comment by mschinca** [comment]
@Febbe I noticed this line in `cmake` output:
```
-- Found X11: /Users/me/gtk/inst/include
```
so I believe the gtk version built via macports (and probably the brew one) let CMake think that there is some X11 installed even if there is not one.
I was wondering if a solution along these lines could be acceptable (tested locally):

```
-if(X11_FOUND AND X11_Xi_FOUND)
+if(X11_FOUND AND X11_Xi_FOUND AND NOT APPLE)
```

**Comment by mschinca** [comment]
Trying the `brew` method, ```cmake``` outputs this line instead:
```
- Found X11: /usr/local/include
``` 
the X11 folder contains symlinks to headers installed by packages `xorgproto`, `libx11` and `libxdmcp`, which are dependencies of `gtk+3 (3.24.28)`
